apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: reur
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reur
    app.kubernetes.io/part-of: byoc-app-szbz
  name: reurhhnv
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: reur
    weight: null
status: {}
