apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: reur
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reur
    app.kubernetes.io/part-of: byoc-app-szbz
  name: reur
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: reur
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: reur
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-nrem-tenant/byoc-app-szbz/reur@sha256:464f996b1dec652f236e449459586990c99ec8414880a8f63ac68ec7535511fc
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
